// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmcIBuEiGfu8jX8xk3jc6py2Ar9dNj_DY',
    appId: '1:12528183634:web:ffd32ac530c4fef1bc728b',
    messagingSenderId: '12528183634',
    projectId: 'production-pockeat',
    authDomain: 'production-pockeat.firebaseapp.com',
    storageBucket: 'production-pockeat.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUz7Lk2w2-0d-Uf3GT2BCqnkNhP9riL70',
    appId: '1:12528183634:android:1e8d9629a10880d4bc728b',
    messagingSenderId: '12528183634',
    projectId: 'production-pockeat',
    storageBucket: 'production-pockeat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz0c4_GQHXELXrAZROV4ECc-UEt3QZSXo',
    appId: '1:12528183634:ios:7ad41184750abbc2bc728b',
    messagingSenderId: '12528183634',
    projectId: 'production-pockeat',
    storageBucket: 'production-pockeat.firebasestorage.app',
    iosBundleId: 'com.pockeat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCz0c4_GQHXELXrAZROV4ECc-UEt3QZSXo',
    appId: '1:12528183634:ios:6d2412bf6560c41ebc728b',
    messagingSenderId: '12528183634',
    projectId: 'production-pockeat',
    storageBucket: 'production-pockeat.firebasestorage.app',
    iosBundleId: 'com.example.amankendara',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmcIBuEiGfu8jX8xk3jc6py2Ar9dNj_DY',
    appId: '1:12528183634:web:35beb58f0e85feefbc728b',
    messagingSenderId: '12528183634',
    projectId: 'production-pockeat',
    authDomain: 'production-pockeat.firebaseapp.com',
    storageBucket: 'production-pockeat.firebasestorage.app',
  );
}
