name: Staging CI

on:
  push:
    branches: [staging]
  pull_request:
    branches: [staging]

jobs:
  test:
    name: Tests & Analysis
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'
          channel: 'stable'
          cache: true
      
      - name: Create .env file
        run: |
          echo "FLAVOR=staging" > .env
          echo "STAGING_FIREBASE_PROJECT_ID=${{ secrets.STAGING_FIREBASE_PROJECT_ID }}" >> .env
          echo "STAGING_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.STAGING_FIREBASE_MESSAGING_SENDER_ID }}" >> .env
          echo "STAGING_FIREBASE_STORAGE_BUCKET=${{ secrets.STAGING_FIREBASE_STORAGE_BUCKET }}" >> .env
          echo "STAGING_FIREBASE_ANDROID_APP_ID=${{ secrets.STAGING_FIREBASE_ANDROID_APP_ID }}" >> .env
          echo "STAGING_FIREBASE_ANDROID_API_KEY=${{ secrets.STAGING_FIREBASE_ANDROID_API_KEY }}" >> .env
          echo "STAGING_FIREBASE_IOS_APP_ID=${{ secrets.STAGING_FIREBASE_IOS_APP_ID }}" >> .env
          echo "STAGING_FIREBASE_IOS_API_KEY=${{ secrets.STAGING_FIREBASE_IOS_API_KEY }}" >> .env
          echo "STAGING_FIREBASE_IOS_BUNDLE_ID=${{ secrets.STAGING_FIREBASE_IOS_BUNDLE_ID }}" >> .env
          echo "STAGING_FIREBASE_WEB_APP_ID=${{ secrets.STAGING_FIREBASE_WEB_APP_ID }}" >> .env
          echo "STAGING_FIREBASE_WEB_API_KEY=${{ secrets.STAGING_FIREBASE_WEB_API_KEY }}" >> .env
          echo "STAGING_FIREBASE_AUTH_DOMAIN=${{ secrets.STAGING_FIREBASE_AUTH_DOMAIN }}" >> .env

      - name: Get dependencies
        run: flutter pub get
        
      - name: Run Flutter Analyze
        run: |
          mkdir -p analysis-results
          flutter analyze --no-fatal-warnings --no-fatal-infos > analysis-results/flutter-analyze.txt || true
          
      - name: Generate HTML report from Flutter Analyze
        run: |
          echo '<html><head><title>Flutter Analysis Report</title>' > analysis-results/analysis-report.html
          echo '<style>
            body { font-family: Arial, sans-serif; margin: 20px; }
            h1 { color: #1389FD; }
            .error { color: red; }
            .warning { color: orange; }
            .info { color: blue; }
            pre { background-color: #f5f5f5; padding: 10px; border-radius: 5px; }
          </style>' >> analysis-results/analysis-report.html
          echo '</head><body>' >> analysis-results/analysis-report.html
          echo '<h1>Flutter Analysis Report</h1>' >> analysis-results/analysis-report.html
          
          echo '<pre>' >> analysis-results/analysis-report.html
          cat analysis-results/flutter-analyze.txt | sed 's/\x1B\[[0-9;]*[JKmsu]//g' | sed 's/&/\&amp;/g; s/</\&lt;/g; s/>/\&gt;/g' >> analysis-results/analysis-report.html
          echo '</pre>' >> analysis-results/analysis-report.html
          
          # Extract and count issues
          ERRORS=$(grep -c "error" analysis-results/flutter-analyze.txt || echo "0")
          WARNINGS=$(grep -c "warning" analysis-results/flutter-analyze.txt || echo "0")
          INFOS=$(grep -c "info" analysis-results/flutter-analyze.txt || echo "0")
          
          echo '<div style="margin-top: 20px; padding: 10px; background-color: #f0f0f0; border-radius: 5px;">' >> analysis-results/analysis-report.html
          echo "<p><strong>Summary:</strong> Found $ERRORS errors, $WARNINGS warnings, and $INFOS info issues.</p>" >> analysis-results/analysis-report.html
          echo '</div>' >> analysis-results/analysis-report.html
          
          echo '</body></html>' >> analysis-results/analysis-report.html
          
      - name: Upload Analysis Report
        uses: actions/upload-artifact@v4
        with:
          name: flutter-analysis-report
          path: analysis-results/analysis-report.html
          
      - name: Install junitreport for test results
        run: dart pub global activate junitreport
        
      - name: Run tests with coverage and generate JUnit report
        run: |
          mkdir -p test-results
          flutter test --coverage --machine | tee test_output.json
          dart pub global run junitreport:tojunit --input test_output.json --output test-results/junit.xml
        
      - name: Rename JUnit file to match Codecov expectations
        run: |
          cp test-results/junit.xml test-results/junit-flutter-tests.xml
          
      - name: Prepare coverage report
        run: |
          mkdir -p coverage/combined
          cp coverage/lcov.info coverage/combined/lcov.info
        
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/combined/lcov.info
          fail_ci_if_error: true
      
      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: test-results/junit-flutter-tests.xml
          
      - name: Display Codecov link
        run: |
          COMMIT_SHA="${{ github.event.pull_request.head.sha || github.sha }}"
          REPO_NAME="${{ github.repository }}"
          echo "Code Coverage Report: https://codecov.io/gh/${REPO_NAME}/commit/${COMMIT_SHA}"

  build:
    name: Build Debug APK
    needs: test
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'
          channel: 'stable'
          cache: true
          
      - name: Create .env file
        run: |
          echo "FLAVOR=staging" > .env
          echo "STAGING_FIREBASE_PROJECT_ID=${{ secrets.STAGING_FIREBASE_PROJECT_ID }}" >> .env
          echo "STAGING_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.STAGING_FIREBASE_MESSAGING_SENDER_ID }}" >> .env
          echo "STAGING_FIREBASE_STORAGE_BUCKET=${{ secrets.STAGING_FIREBASE_STORAGE_BUCKET }}" >> .env
          echo "STAGING_FIREBASE_ANDROID_APP_ID=${{ secrets.STAGING_FIREBASE_ANDROID_APP_ID }}" >> .env
          echo "STAGING_FIREBASE_ANDROID_API_KEY=${{ secrets.STAGING_FIREBASE_ANDROID_API_KEY }}" >> .env
          echo "STAGING_FIREBASE_IOS_APP_ID=${{ secrets.STAGING_FIREBASE_IOS_APP_ID }}" >> .env
          echo "STAGING_FIREBASE_IOS_API_KEY=${{ secrets.STAGING_FIREBASE_IOS_API_KEY }}" >> .env
          echo "STAGING_FIREBASE_IOS_BUNDLE_ID=${{ secrets.STAGING_FIREBASE_IOS_BUNDLE_ID }}" >> .env
          echo "STAGING_FIREBASE_WEB_APP_ID=${{ secrets.STAGING_FIREBASE_WEB_APP_ID }}" >> .env
          echo "STAGING_FIREBASE_WEB_API_KEY=${{ secrets.STAGING_FIREBASE_WEB_API_KEY }}" >> .env
          echo "STAGING_FIREBASE_AUTH_DOMAIN=${{ secrets.STAGING_FIREBASE_AUTH_DOMAIN }}" >> .env
      
      - name: Get dependencies
        run: flutter pub get
        
      - name: Build Debug APK
        run: flutter build apk --debug
        
      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: build/app/outputs/flutter-apk/app-debug.apk